###
# LibrosController Endpoints
###

# Obtener todos los libros
GET http://localhost:8080/api/libros

# Obtener un libro por ID
###
GET http://localhost:8080/api/libros/1

###
# Crear un nuevo libro
POST http://localhost:8080/api/libros
Content-Type: application/json

{
  "titulo": "El Quijote",
  "descripcion": "Una novela clásica",
  "portadaUrl": "http://example.com/portada.jpg",
  "formato": "Hardcover",
  "fechaPublicacion": "1605-01-16",
  "isbn": "123456124",
  "numeroPaginas": 101
}

###
# Actualizar un libro por ID
PUT http://localhost:8080/api/libros/1
Content-Type: application/json

{
  "titulo": "El Quijote",
  "descripcion": "Una novela clásica",
  "portadaUrl": "http://example.com/portada.jpg",
  "formato": "Hardcover",
  "fechaPublicacion": "1605-01-16",
  "isbn": "123456124",
  "numeroPaginas": 108
}
###
# Eliminar un libro por ID
DELETE http://localhost:8080/api/libros/1